/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current identity and workspace memberships. Login (/oauth2/authorization/entra) and logout (/logout) are browser-redirect flows, not JSON operations, and are not modeled here. Effective capabilities are added once authorization checks exist. */
        get: operations["getCurrentIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/probes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a platform self-check message. */
        post: operations["createPlatformProbe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/probes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read back a previously recorded platform self-check message. */
        get: operations["getPlatformProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every document in the workspace, most recently created first, as a lightweight summary without full revision content. Not paginated yet. */
        get: operations["listDocuments"];
        put?: never;
        /** Create a document with its initial immutable revision. */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a document and its selected immutable revision. */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Apply typed edits against the expected current revision. */
        patch: operations["patchDocumentContent"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/fields/review-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Records a person's own review decision for one field or repeated item, independent of its value, evidence, authorship, and lock. */
        post: operations["recordReviewDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/fields/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explicitly sets one field or repeated item's lock -- the only route that ever changes it deliberately. */
        post: operations["setFieldLock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable revision history in ascending revision order. */
        get: operations["listDocumentRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one immutable revision. */
        get: operations["getDocumentRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start grounded fact extraction for a document from an attached source. Returns immediately with a durable job to poll via GET .../jobs/{jobId}; the trusted worker performs the actual model call asynchronously. Today's first real slice covers extraction only, not composition or question resolution. */
        post: operations["startExtraction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/generations/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The artifact a finished extraction job published, if any. 404 until the worker publishes one; poll GET .../jobs/{jobId} for the job's own state first. */
        get: operations["getExtractionResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/generations/{jobId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This job's own open questions, materializing them the first time they are asked for once the job leaves itself WAITING_FOR_INPUT (poll GET .../jobs/{jobId} for that state first). Empty until then. */
        get: operations["getGenerationQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/generations/{jobId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turns this finished job's own published result into a real, reviewable patch proposal against the document's current revision. Nothing is applied to the document yet -- see POST .../patch-proposals/{proposalId}/accept. */
        post: operations["applyGenerationResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/generations/{jobId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freezes every currently answered question for this document and requests the worker pick this job back up. A question left open is simply not included; the worker's own re-detection raises it again if so, the same durable wait as before. */
        post: operations["resumeGenerationAfterQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authoritative durable job state. */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cooperative cancellation of a non-terminal job. */
        post: operations["requestJobCancellation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/jobs/{jobId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a durable human-wait job eligible for another claim. */
        post: operations["resumeWaitingJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream persisted progress events. Reconnect with Last-Event-ID. */
        get: operations["streamWorkspaceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/events/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll persisted progress events when SSE is unavailable. */
        get: operations["pollWorkspaceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Allocate an owned artifact upload. */
        post: operations["allocateUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/uploads/{artifactId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stream an allocated artifact's bytes. Content is immutable once received. */
        put: operations["uploadArtifactContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/uploads/{artifactId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify and finalize an uploaded artifact, scanning it for malware. */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/artifacts/{artifactId}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run structural extraction on a READY artifact. Always returns 200 with whichever terminal outcome extraction actually reached (COMPLETE, UNSUPPORTED, or FAILED); a real HTTP error means the request itself could not be attempted. */
        post: operations["extractArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every template in the workspace (both ACTIVE and DRAFT), in creation order. A caller building a document-creation picker filters to entries with a non-null currentActiveVersionId itself. */
        get: operations["listTemplates"];
        put?: never;
        /** Creates a new custom template's own draft against an already- extracted DOCX source. Deliberately returns the draft version alongside the template, since a caller needs that version's own number for the very next PUT .../draft/bindings call. */
        post: operations["createTemplateDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/draft/candidate-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidate field bindings proposed from the draft's own extracted structure -- a starting point offered back for review, never applied by itself. A caller still submits its own chosen fields through PUT .../draft/bindings. */
        get: operations["getDraftCandidateBindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/draft/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Validates every field's binding against the draft's own pinned extraction graph before persisting anything -- a rejected set of bindings never partially lands. */
        put: operations["replaceDraftBindings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activates the draft's current version after re-validating its bindings and rules and proving a real sample fill and render -- refuses an empty field list. */
        post: operations["activateTemplateVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One template version by its own ID, including its field definitions -- read before creating a document against an ACTIVATED version. */
        get: operations["getTemplateVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every rule proposed against the template's current open draft version, in the order proposed. */
        get: operations["listRules"];
        put?: never;
        /** Proposes one rule against the template's own currently open draft version, validated against that draft's real field definitions and pinned extraction graph before anything is persisted. */
        post: operations["proposeRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One rule by its own ID. */
        get: operations["getRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/rules/{ruleId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accepts a proposed rule as-is. Accepting a PROTECTED_REGION rule is this app's own "lock a region" action -- a person locks a region by accepting exactly that proposal, not through a separate mechanism. */
        post: operations["acceptRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/templates/{templateId}/rules/{ruleId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rejects a proposed rule. There is no separate edit route -- "editing" a rejected rule is proposing a fresh one with the corrected payload. */
        post: operations["rejectRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach a READY artifact as a source, or return the snapshot that already does. */
        post: operations["attachSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/documents/{documentId}/patch-proposals/{proposalId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Applies only the still-CLEAN subset of a proposal against the document's real current revision -- a conflicting or locked field is left exactly as it is, reported rather than silently skipped. */
        post: operations["acceptPatchProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/questions/{questionId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer one open question. There is no route back to OPEN and no route to change an existing answer. */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MeResponse: {
            /** Format: int64 */
            userId: number;
            issuer: string;
            subject: string;
            email?: string;
            displayName?: string;
            memberships: components["schemas"]["MembershipResponse"][];
        };
        MembershipResponse: {
            /** Format: int64 */
            workspaceId: number;
            /** @description Only OWNER exists until team workspaces are supported. */
            role: string;
        };
        CreateProbeRequest: {
            message: string;
        };
        ProbeResponse: {
            /** Format: int64 */
            id: number;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateDocumentRequest: {
            title: string;
            /** Format: int64 */
            templateId: number;
            /** Format: int64 */
            templateVersionId: number;
            fields: {
                [key: string]: components["schemas"]["FieldValueRequest"];
            };
            initialRevisionReason: string;
        };
        PatchDocumentContentRequest: {
            /** Format: int64 */
            expectedRevisionId: number;
            edits: components["schemas"]["FieldEditRequest"][];
            editReason: string;
        };
        RecordReviewDecisionRequest: {
            /** Format: int64 */
            expectedRevisionId: number;
            fieldId: string;
            /** @description Present only for one row of a repeated field; omitted for a whole scalar field. */
            itemIndex?: number | null;
            /** @enum {string} */
            decision: "UNREVIEWED" | "ACCEPTED" | "REJECTED" | "NEEDS_CLARIFICATION";
            /** @description Defaults to a fixed reason when blank or omitted. */
            editReason?: string | null;
        };
        SetFieldLockRequest: {
            /** Format: int64 */
            expectedRevisionId: number;
            fieldId: string;
            /** @description Present only for one row of a repeated field; omitted for a whole scalar field. */
            itemIndex?: number | null;
            /** @enum {string} */
            lock: "EDITABLE" | "PRESERVE_ON_REGENERATION" | "EXPLICITLY_LOCKED";
            /** @description Defaults to a fixed reason when blank or omitted. */
            editReason?: string | null;
        };
        FieldEditRequest: {
            /** @enum {string} */
            operation: "SET" | "CLEAR";
            fieldId: string;
            value?: components["schemas"]["FieldValueRequest"];
        };
        FieldValueRequest: {
            /** @enum {string} */
            type: "TEXT" | "DATE";
            /** @enum {string} */
            cardinality: "SCALAR" | "REPEATED";
            value?: string;
            values?: string[];
        };
        FieldValueResponse: {
            /** @enum {string} */
            type: "TEXT" | "DATE";
            /** @enum {string} */
            cardinality: "SCALAR" | "REPEATED";
            value?: string | null;
            values?: string[] | null;
            evidenceSourceSpanIds?: number[];
            /** @description Present for a SCALAR field. */
            fieldState?: components["schemas"]["FieldStateResponse"] | null;
            /** @description Present for a REPEATED field, one entry per item in the same order as values. */
            itemFieldStates?: (components["schemas"]["FieldStateResponse"] | null)[] | null;
        };
        FieldStateResponse: {
            /** @enum {string} */
            authorship: "IMPORTED" | "AI_COMPOSED" | "USER_AUTHORED" | "MIXED";
            /** @enum {string} */
            evidenceSupport: "DIRECT" | "TRANSFORMED" | "AMBIGUOUS" | "UNSUPPORTED" | "MISSING";
            /** @enum {string} */
            validation: "NOT_RUN" | "PASSED" | "WARNING" | "BLOCKING" | "UNAVAILABLE";
            /** @enum {string} */
            review: "UNREVIEWED" | "ACCEPTED" | "REJECTED" | "NEEDS_CLARIFICATION";
            /** @enum {string} */
            lock: "EDITABLE" | "PRESERVE_ON_REGENERATION" | "EXPLICITLY_LOCKED";
        };
        DocumentRevisionResponse: {
            /** Format: int64 */
            id: number;
            revisionNumber: number;
            /** Format: int64 */
            parentRevisionId?: number | null;
            fields: {
                [key: string]: components["schemas"]["FieldValueResponse"];
            };
            contentHash: string;
            editReason: string;
            /** Format: date-time */
            createdAt: string;
        };
        DocumentResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            templateId: number;
            /** Format: int64 */
            templateVersionId: number;
            /** Format: int64 */
            currentRevisionId: number;
            /** Format: date-time */
            createdAt: string;
            currentRevision: components["schemas"]["DocumentRevisionResponse"];
        };
        CommandReceiptResponse: {
            /** Format: uuid */
            commandId: string;
            /** Format: int64 */
            jobId: number;
            operation: string;
            /** @enum {string} */
            status: "ACCEPTED";
            /** Format: date-time */
            acceptedAt: string;
        };
        JobResponse: {
            /** Format: int64 */
            id: number;
            type: string;
            resourceType: string;
            /** Format: int64 */
            resourceId: number;
            /** Format: int64 */
            resourceVersion: number;
            stage: string;
            state: string;
            attemptCount: number;
            /** Format: date-time */
            availableAt: string;
            /** Format: date-time */
            deadlineAt: string;
            /** Format: date-time */
            cancellationRequestedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EventResponse: {
            /** Format: int64 */
            eventId: number;
            /** Format: int64 */
            workspaceId: number;
            /** Format: int64 */
            jobId: number;
            resourceType: string;
            /** Format: int64 */
            resourceId: number;
            /** Format: int64 */
            resourceVersion: number;
            stage: string;
            /** Format: int64 */
            jobSequence: number;
            type: string;
            state: string;
            message?: string | null;
            progressCurrent?: number | null;
            progressTotal?: number | null;
            /** Format: date-time */
            occurredAt: string;
        };
        EventBatchResponse: {
            resyncRequired: boolean;
            /** Format: int64 */
            nextEventId: number;
            events: components["schemas"]["EventResponse"][];
        };
        /** @description The shape of every error response in this API, regardless of cause. */
        Error: {
            status: number;
            title: string;
            detail?: string;
            instance?: string;
            /** @description Stable, machine-readable error code (e.g. NOT_FOUND, VALIDATION_FAILED). */
            code: string;
            /** @description Echoes the X-Correlation-Id request/response header. */
            correlationId: string;
            fields: {
                field?: string;
                message?: string;
            }[];
            recoveryActions: string[];
            /** @description Present only when code is RULE_VALIDATION_FAILED: one entry per way the proposed rule's payload does not hold against the draft's own field definitions. */
            problems?: {
                reason?: string;
                detail?: string;
            }[];
        };
        DocumentSummaryResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: int64 */
            templateId: number;
            /** Format: int64 */
            templateVersionId: number;
            /** Format: int64 */
            currentRevisionId: number;
            /** Format: date-time */
            createdAt: string;
        };
        AllocateUploadRequest: {
            /** @description Client-supplied filename, sanitized server-side into display metadata. */
            filename?: string;
        };
        ArtifactResponse: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "UPLOADING" | "QUARANTINED" | "SCANNING" | "READY" | "REJECTED";
            /** Format: int64 */
            byteCount?: number | null;
            sha256?: string | null;
            /** @enum {string|null} */
            detectedMediaType?: "DOCX" | "PDF" | "PLAIN_TEXT" | null;
            displayFilename?: string | null;
            rejectionReason?: string | null;
        };
        /** @description The full shape carries format-specific fields (feature findings for DOCX, page geometry for PDF) not modeled here yet -- the frontend workspace only needs the terminal status today. */
        ExtractionResponse: {
            /** @enum {string} */
            status: "COMPLETE" | "UNSUPPORTED" | "FAILED";
            parserVersion?: string | null;
            failureReason?: string | null;
        };
        TemplateResponse: {
            /** Format: int64 */
            id: number;
            displayName: string;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE";
            /** Format: int64 */
            currentActiveVersionId?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        FieldDefinitionResponse: {
            fieldId: string;
            /** @enum {string} */
            type: "TEXT" | "DATE";
            /** @enum {string} */
            cardinality: "SCALAR" | "REPEATED";
            /** @enum {string} */
            requiredness: "REQUIRED" | "OPTIONAL";
            /** @enum {string} */
            bindingKind: "CONTENT_CONTROL_TAG" | "STRUCTURAL_NODE";
            tag?: string | null;
            part?: string | null;
            nodeId?: string | null;
        };
        TemplateVersionResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            templateId: number;
            versionNumber: number;
            /** Format: int64 */
            sourceArtifactId: number;
            /** Format: int64 */
            extractionVersionId: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVATED";
            fields: components["schemas"]["FieldDefinitionResponse"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            activatedAt?: string | null;
        };
        CreateTemplateRequest: {
            displayName: string;
            /** Format: int64 */
            sourceArtifactId: number;
        };
        TemplateDraftResponse: {
            template: components["schemas"]["TemplateResponse"];
            draftVersion: components["schemas"]["TemplateVersionResponse"];
        };
        /** @description Only tag (for CONTENT_CONTROL_TAG) or part/nodeId (for STRUCTURAL_NODE) is required, chosen by kind; the other is ignored. */
        BindingRequest: {
            /** @enum {string} */
            kind: "CONTENT_CONTROL_TAG" | "STRUCTURAL_NODE";
            tag?: string | null;
            part?: string | null;
            nodeId?: string | null;
        };
        FieldDefinitionRequest: {
            fieldId: string;
            /** @enum {string} */
            type: "TEXT" | "DATE";
            /** @enum {string} */
            cardinality: "SCALAR" | "REPEATED";
            /** @enum {string} */
            requiredness: "REQUIRED" | "OPTIONAL";
            binding: components["schemas"]["BindingRequest"];
        };
        ReplaceBindingsRequest: {
            expectedVersionNumber: number;
            fields: components["schemas"]["FieldDefinitionRequest"][];
        };
        ActivateVersionRequest: {
            expectedVersionNumber: number;
        };
        CandidateFieldBindingResponse: {
            fieldId: string;
            /** @enum {string} */
            type: "TEXT" | "DATE";
            /** @enum {string} */
            cardinality: "SCALAR" | "REPEATED";
            contentControlTag: string;
        };
        CandidateBindingReportResponse: {
            candidates: components["schemas"]["CandidateFieldBindingResponse"][];
            ambiguousContentControlTags: string[];
        };
        AttachSourceRequest: {
            /** Format: int64 */
            artifactId: number;
        };
        SnapshotResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            artifactId: number;
            kind: string;
            /** Format: date-time */
            fetchedAt: string;
        };
        StartExtractionRequest: {
            /** Format: int64 */
            sourceArtifactId: number;
        };
        ExtractionResultResponse: {
            /**
             * Format: int64
             * @description Download this artifact's bytes through the existing generic /uploads/{artifactId}/download route.
             */
            artifactId: number;
        };
        QuestionCandidateOptionResponse: {
            value: string;
            evidenceSpanIds: number[];
        };
        QuestionResponse: {
            /** Format: int64 */
            id: number;
            fieldId: string;
            /** @enum {string} */
            reason: "MISSING_REQUIRED" | "CONFLICT";
            candidates: components["schemas"]["QuestionCandidateOptionResponse"][];
            /** @enum {string} */
            status: "OPEN" | "ANSWERED";
            answerValue?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AnswerQuestionRequest: {
            answerValue: string;
        };
        ProposedFieldResponse: {
            /** @enum {string} */
            type: "TEXT" | "DATE";
            value: string;
            evidenceSpanIds: number[];
        };
        PatchProposalResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            documentId: number;
            /** Format: int64 */
            baseRevisionId: number;
            proposedValues: {
                [key: string]: components["schemas"]["ProposedFieldResponse"];
            };
            /** @enum {string} */
            status: "PROPOSED" | "ACCEPTED";
            /** Format: date-time */
            createdAt: string;
        };
        AcceptPatchProposalRequest: {
            /** Format: int64 */
            expectedRevisionId: number;
            /** @description Defaults to a fixed reason when blank or omitted. */
            editReason?: string | null;
        };
        PatchAcceptResponse: {
            applied: boolean;
            fieldStatuses: {
                [key: string]: "CLEAN" | "CONFLICT" | "LOCKED";
            };
            /** @description Present only when at least one field actually applied. */
            revision?: components["schemas"]["DocumentRevisionResponse"] | null;
        };
        /** @description fieldId is required only for a SINGLE_FIELD scope; ignored for WHOLE_TEMPLATE. */
        RuleScopeRequest: {
            /** @enum {string} */
            kind: "WHOLE_TEMPLATE" | "SINGLE_FIELD";
            fieldId?: string | null;
        };
        /** @description One flat shape for all ten rule payload kinds -- the same "only the sub-fields the chosen kind actually needs are populated" convention FieldDefinitionRequest's own binding already establishes for choosing a field binding's own two kinds; every other property is omitted or null. */
        RulePayloadRequest: {
            /** @enum {string} */
            kind: "REQUIRED_FIELDS" | "MAX_TEXT_LENGTH" | "MAX_ITEM_COUNT" | "ALLOWED_SECTION_ORDER" | "DATE_DISPLAY_FORMAT" | "ALLOWED_SOURCE_KINDS" | "MISSING_VALUE_BEHAVIOR" | "ALLOWED_OVERFLOW_BEHAVIOR" | "REPEATABLE_REGION_EMPTY_BEHAVIOR" | "PROTECTED_REGION";
            /** @description Required by every kind except REQUIRED_FIELDS, ALLOWED_SECTION_ORDER, and PROTECTED_REGION. */
            fieldId?: string | null;
            /** @description REQUIRED_FIELDS only -- one or more real field IDs. */
            fieldIds?: string[] | null;
            /** @description MAX_TEXT_LENGTH only. */
            maxCharacters?: number | null;
            /** @description MAX_ITEM_COUNT only. */
            maxItems?: number | null;
            /** @description ALLOWED_SECTION_ORDER only -- a freeform ordered list of section identifiers the person types themselves. */
            orderedSectionIds?: string[] | null;
            /**
             * @description DATE_DISPLAY_FORMAT only.
             * @enum {string|null}
             */
            dateFormatStyle?: "LONG" | "SHORT" | "ISO" | null;
            /** @description ALLOWED_SOURCE_KINDS only -- ARTIFACT is the only source kind this codebase produces today. */
            allowedSourceKinds?: "ARTIFACT"[] | null;
            /**
             * @description MISSING_VALUE_BEHAVIOR or REPEATABLE_REGION_EMPTY_BEHAVIOR only.
             * @enum {string|null}
             */
            emptyValueResolution?: "OMIT" | "BLANK" | "PLACEHOLDER_TEXT" | null;
            /**
             * @description ALLOWED_OVERFLOW_BEHAVIOR only.
             * @enum {string|null}
             */
            overflowResolution?: "BLOCK_EXPORT" | "ALLOW_REFLOW" | null;
            /** @description PROTECTED_REGION only. */
            protectedRegionTarget?: components["schemas"]["BindingRequest"] | null;
        };
        ProposeRuleRequest: {
            scope: components["schemas"]["RuleScopeRequest"];
            payload: components["schemas"]["RulePayloadRequest"];
            humanExplanation?: string | null;
        };
        RuleResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            templateId: number;
            /** Format: int64 */
            templateVersionId: number;
            /** @enum {string} */
            category: "VISUAL" | "CONTENT" | "BEHAVIOR" | "VALIDATION" | "SOURCE";
            scope: components["schemas"]["RuleScopeRequest"];
            payload: components["schemas"]["RulePayloadRequest"];
            /** @enum {string} */
            status: "PROPOSED" | "ACCEPTED" | "REJECTED";
            humanExplanation?: string | null;
            /** Format: int64 */
            authorUserId: number;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource is not visible in this workspace. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with the current state or an idempotency key. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
        /** @description The typed request is well formed but semantically invalid. */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        WorkspaceId: number;
        DocumentId: number;
        RevisionId: number;
        JobId: number;
        ArtifactId: number;
        TemplateId: number;
        VersionId: number;
        QuestionId: number;
        RuleId: number;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Not logged in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPlatformProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProbeRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    /** @description URL of the created probe. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description Validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPlatformProbe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description No probe with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's documents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummaryResponse"][];
                };
            };
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Created, or the stable result of an idempotent replay. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchDocumentContent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchDocumentContentRequest"];
            };
        };
        responses: {
            /** @description The newly selected revision, or the stable result of an idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRevisionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description The expected revision is no longer current. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["UnprocessableContent"];
        };
    };
    recordReviewDecision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description The newly appended revision, or the stable result of an idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRevisionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description The expected revision is no longer current. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    setFieldLock: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetFieldLockRequest"];
            };
        };
        responses: {
            /** @description The newly appended revision, or the stable result of an idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRevisionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description The expected revision is no longer current. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDocumentRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revision history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRevisionResponse"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDocumentRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRevisionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    startExtraction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExtractionRequest"];
            };
        };
        responses: {
            /** @description Accepted, or the stable result of an idempotent replay. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceiptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    getExtractionResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResultResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getGenerationQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This job's own questions, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"][];
                };
            };
        };
    };
    applyGenerationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchProposalResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    resumeGenerationAfterQuestions: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceiptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    requestJobCancellation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceiptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeWaitingJob: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandReceiptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    streamWorkspaceEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent event stream. A resync-required event instructs the client to fetch authoritative state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Concurrent stream limit reached. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    pollWorkspaceEvents: {
        parameters: {
            query?: {
                afterEventId?: number;
                limit?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events after the cursor, or a resynchronization instruction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventBatchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    allocateUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AllocateUploadRequest"];
            };
        };
        responses: {
            /** @description Allocated, awaiting content. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
        };
    };
    uploadArtifactContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                artifactId: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Content received and classified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            /** @description The upload exceeds the configured size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description The uploaded content is not a supported media type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                artifactId: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A real terminal or retryable outcome (READY, REJECTED, or still QUARANTINED after a scanner failure) -- not necessarily success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    extractArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                artifactId: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The extraction's terminal outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace's templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
        };
    };
    createTemplateDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDraftResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    getDraftCandidateBindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The draft's own proposed candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateBindingReportResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceDraftBindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceBindingsRequest"];
            };
        };
        responses: {
            /** @description The draft's own newly appended version, with these bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateVersionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    activateTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateVersionRequest"];
            };
        };
        responses: {
            /** @description Activated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateVersionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    getTemplateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateVersionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The draft's own proposed rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"][];
                };
            };
            /** @description The template does not exist, or has no currently open draft version. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    proposeRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRuleRequest"];
            };
        };
        responses: {
            /** @description Proposed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The template does not exist, or has no currently open draft version to propose a rule against. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["UnprocessableContent"];
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acceptRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description The rule does not exist, or is no longer PROPOSED. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    rejectRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                templateId: components["parameters"]["TemplateId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description The rule does not exist, or is no longer PROPOSED. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    attachSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachSourceRequest"];
            };
        };
        responses: {
            /** @description Attached. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    acceptPatchProposal: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                documentId: components["parameters"]["DocumentId"];
                proposalId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptPatchProposalRequest"];
            };
        };
        responses: {
            /** @description Acted on -- check `applied`; a fully blocked proposal still returns 200 with every field reported. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchAcceptResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionRequest"];
            };
        };
        responses: {
            /** @description Answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
